name = "hex-gfq-ring"
defaultTargets = ["HexGFqRing"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "6bb30a50196b830b5faeead8580b1bd889069717"

[[require]]
name = "HexModArith"
git = "https://github.com/leanprover/hex-mod-arith.git"
rev = "b4d0be9f888af0ff79169423144599d649cd969a"

[[lean_lib]]
name = "HexGFqRing"
