name = "hex-gfq-ring"
defaultTargets = ["HexGFqRing"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "3d2cc1c30b0e17dfec35858e9d5fa8d75e1f241b"

[[lean_lib]]
name = "HexGFqRing"
