name = "hex-gfq-ring"
defaultTargets = ["HexGFqRing"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPolyFp"
git = "https://github.com/leanprover/hex-poly-fp.git"
rev = "63d11e9652020e83629808977bff618e99d21234"

[[lean_lib]]
name = "HexGFqRing"
